org: 1garo
app: my-aws-python-flask-api-app
service: my-aws-python-flask-api-app

frameworkVersion: '2'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
